(()=>{
 const page=$('page-dashboard');
 page.innerHTML=`<div class="dashboard-heading"><div><div class="tiny-label">YOUR OWN VIEW</div><h2>Keep the useful things close.</h2><p class="page-description">Cards run taught skills on your schedule. Their content and next refresh stay in graph memory.</p></div><div class="dashboard-live"><span>●</span> Refreshes while the server runs</div></div>
 <div class="dashboard-actions"><button class="primary" id="dashboard-weather">＋ Today's weather</button><button class="secondary" id="dashboard-date">＋ Local date</button><button class="secondary" id="dashboard-custom">＋ Custom card</button><span id="dashboard-summary"></span></div>
 <p id="dashboard-feedback" role="status"></p>
 <form id="dashboard-question" class="dashboard-question" hidden><label id="dashboard-question-label" for="dashboard-reply"></label><div><input id="dashboard-reply" aria-label="Dashboard clarification" placeholder="Paste a public page URL, or cancel" required><button type="submit" class="primary">Reply</button></div></form>
 <div id="dashboard-cards" class="dashboard-cards"></div>
 <details id="dashboard-authoring"><summary>Add a card from a taught skill</summary><form id="dashboard-form" class="dashboard-form"><label>Card title<input id="dashboard-title" placeholder="Something to keep an eye on" required maxlength="100"></label><label>Taught skill<input id="dashboard-method" list="dashboard-methods" placeholder="Procedure name" required><datalist id="dashboard-methods"></datalist></label><label>Refresh every (minutes)<input id="dashboard-minutes" type="number" value="60" min="1" max="525600" step="1" required></label><label class="dashboard-input-label">Skill input (JSON)<textarea id="dashboard-argument" rows="3" spellcheck="false">null</textarea></label><button class="primary" type="submit">Add card</button></form><p class="sense-hint">The selected procedure will execute automatically, including its actions. Text, values and lists display as data; cards cannot inject HTML or scripts.</p></details>
 <div class="dashboard-teach-note"><span class="tiny-label">TRY SAYING</span><p>“Add today's weather to my dashboard and refresh it every 30 minutes.”</p><p class="sense-hint">Then: “Refresh it every 2 hours.” Weather currently uses the taught page reader; unsupported layouts show an error.</p></div>`;
 async function run(name,argument){if(busy)return;const feedback=$('dashboard-feedback');feedback.textContent='Updating…';await act('run_skill',null,{name,argument});feedback.textContent=$('error').textContent||'Dashboard updated.';}
 $('dashboard-weather').onclick=()=>run('dashboard_weather',{refresh_seconds:3600});
 $('dashboard-date').onclick=()=>run('dashboard_add',{id:'local-date',title:'Local date',method:'dashboard_date',argument:null,refresh_seconds:3600});
 $('dashboard-custom').onclick=()=>{$('dashboard-authoring').open=true;$('dashboard-title').focus()};
 $('dashboard-form').onsubmit=e=>{e.preventDefault();let argument;try{argument=JSON.parse($('dashboard-argument').value)}catch{$('dashboard-feedback').textContent='Skill input must be valid JSON.';return}run('dashboard_add',{id:$('dashboard-title').value.trim().toLowerCase(),title:$('dashboard-title').value.trim(),method:$('dashboard-method').value.trim(),argument,refresh_seconds:Number($('dashboard-minutes').value)*60})};
 $('dashboard-question').onsubmit=async e=>{e.preventDefault();if(busy)return;const draft=$('input').value;await act('chat',$('dashboard-reply').value);$('input').value=draft;$('dashboard-feedback').textContent=$('error').textContent||'Reply saved.';if(!$('error').textContent)$('dashboard-reply').value=''};
 const date=t=>t?new Date(t*1000).toLocaleString():'Not yet';
 const duration=n=>n%3600===0?(n/3600)+'h':n%60===0?(n/60)+'m':n+'s';
 function showResult(container,result){
  if(result===null||result===undefined){container.append(el('p','dashboard-placeholder','Waiting for its first reading.'));return}
  if(typeof result==='object'&&!Array.isArray(result)){
   if('value' in result){const metric=el('div','dashboard-metric',String(result.value));if(result.unit)metric.append(el('span','',String(result.unit)));container.append(metric)}
   if(result.text)container.append(el('div','dashboard-copy',String(result.text)));
   if(Array.isArray(result.items)){const list=el('ul','dashboard-result-list');for(const item of result.items.slice(0,50))list.append(el('li','',typeof item==='string'?item:JSON.stringify(item)));container.append(list)}
   if(!('value' in result)&&!result.text&&!result.items)container.append(el('pre','',JSON.stringify(result,null,2)));
   if(typeof result.url==='string'){try{const u=new URL(result.url);if(['http:','https:'].includes(u.protocol)){const link=el('a','dashboard-source','Source ↗ '+u.hostname);link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';container.append(link)}}catch{}}
  }else if(Array.isArray(result)){const list=el('ul','dashboard-result-list');for(const item of result.slice(0,50))list.append(el('li','',typeof item==='string'?item:JSON.stringify(item)));container.append(list)}
  else container.append(el('div','dashboard-copy',String(result)));
 }
 const oldRender=render;let seen='',methodsSeen='';render=function(state){oldRender(state);const cards=graphState.dashboard||[];const waiting=graphState.waiting;const asking=waiting?.resume==='dashboard_weather_reply';$('dashboard-question').hidden=!asking;if(asking)$('dashboard-question-label').textContent=waiting.text;
  const methods=Object.keys(graphState.procedures||{}).sort(),mk=methods.join('|');if(mk!==methodsSeen){methodsSeen=mk;$('dashboard-methods').replaceChildren();for(const method of methods){const option=el('option');option.value=method;$('dashboard-methods').append(option)}}
  $('dashboard-summary').textContent=cards.length?cards.length+' cards · '+cards.filter(c=>c.enabled).length+' refreshing':'';
  const key=JSON.stringify(cards);if(key===seen||(document.activeElement?.matches('input,textarea,select')&&document.activeElement.closest('#dashboard-cards')))return;seen=key;$('dashboard-cards').replaceChildren();
  if(!cards.length){const empty=el('div','dashboard-empty');empty.innerHTML='<div class="dashboard-empty-mark">▦</div><h3>A place for things that change.</h3><p>Add weather, a local date, or the output of another taught skill.<br>You choose what belongs here and how often it updates.</p>';$('dashboard-cards').append(empty)}
  for(const card of cards){const article=el('article','dashboard-card');article.dataset.status=card.error?'error':card.enabled?'active':'paused';const head=el('div','dashboard-card-heading');head.append(el('h3','',card.title),el('span','dashboard-badge',!card.enabled?'Paused':card.error?'Refresh failed':card.last_success?'Live · '+duration(card.refresh_seconds):'Waiting'));article.append(head);
   const body=el('div','dashboard-card-body');showResult(body,card.result);article.append(body);
   if(card.error){const error=el('p','dashboard-card-error',(card.last_success?'Showing the last successful result. ':'')+'Refresh failed: '+card.error);error.setAttribute('role','status');article.append(error)}
   const metadata=el('div','dashboard-metadata');metadata.append(el('div','', 'Last success · '+date(card.last_success)),el('div','',card.enabled?'Next attempt · '+date(card.next_at):'Automatic refresh paused'));article.append(metadata);
   const controls=el('div','dashboard-card-actions');const refresh=el('button','secondary','Refresh now');refresh.onclick=()=>run('dashboard_refresh',{id:card.id});const pause=el('button','secondary',card.enabled?'Pause':'Resume');pause.onclick=()=>run('dashboard_enabled',{id:card.id,enabled:!card.enabled});controls.append(refresh,pause);article.append(controls);
   const details=el('details');details.append(el('summary','','Card settings'));const schedule=el('form','dashboard-schedule');const label=el('label','','Refresh every (seconds)');const input=el('input');input.type='number';input.min=60;input.max=31536000;input.step=1;input.value=card.refresh_seconds;input.required=true;label.append(input);const save=el('button','secondary','Save interval');save.type='submit';schedule.append(label,save);schedule.onsubmit=e=>{e.preventDefault();run('dashboard_interval',{id:card.id,refresh_seconds:Number(input.value)})};details.append(schedule,el('p','sense-hint','Taught skill · '+card.method),el('pre','',JSON.stringify(card.argument,null,2)));const remove=el('button','dashboard-remove','Remove card');remove.onclick=()=>run('dashboard_remove',{id:card.id});details.append(remove);article.append(details);$('dashboard-cards').append(article);
  }
 };
})();
