(()=>{
 const section=el('section','language-panel');section.innerHTML=`<div class="state-heading"><div><h2>Words into meaning.</h2><p class="page-description">A starting English / Dutch grammar stored in the graph. Hybrid mode keeps Gemma available for unfamiliar phrasing. Replies may still use English.</p></div><label>Language mode<select id="language-mode"><option value="hybrid">Hybrid · taught grammar + Gemma fallback</option><option value="symbolic">Symbolic · no Gemma fallback</option></select></label></div><p id="language-status" role="status"></p><details><summary>Teach a sentence pattern</summary><form id="language-pattern-form" class="dashboard-form"><label class="dashboard-input-label">Pattern<input id="language-pattern" required value="{subject} woont in {object}" placeholder="{subject} lives in {object}"></label><label>Meaning<select id="language-operation"><option value="assert">Teach a fact</option><option value="query">Check a fact</option><option value="retract">Remove an exact fact</option><option value="describe">Recall a subject</option><option value="find">Find subjects for an object</option></select></label><label>Shared relation<input id="language-relation" value="live in" placeholder="is, live in, like…"></label><button type="submit" class="primary">Teach pattern</button></form><p class="sense-hint">Use {subject} and/or {object}, each at most once. Literal words connect the phrases. This teaches recognition; it does not add an example fact. Conflicting matches ask for clarification.</p></details><details><summary>Teach a word or phrase</summary><form id="language-word-form" class="dashboard-form"><label>Word or phrase<input id="language-word" required placeholder="mens"></label><label>Shared meaning<input id="language-meaning" required placeholder="human"></label><button type="submit" class="primary">Teach word</button></form></details>`;
 $('page-teach').prepend(section);
 async function run(name,argument){if(busy)return;await act('run_skill',null,{name,argument});$('language-status').textContent=$('error').textContent||'Saved in graph memory.'}
 $('language-mode').onchange=()=>run('language_mode',{mode:$('language-mode').value});
 $('language-pattern-form').onsubmit=e=>{e.preventDefault();const pattern=$('language-pattern').value.toLowerCase().trim(),matches=[...pattern.matchAll(/\{(subject|object)\}/g)];const slots=matches.map(m=>m[1]);if(new Set(slots).size!==slots.length||!slots.length||slots.length>2){$('language-status').textContent='Use one or two distinct slots: {subject} and {object}.';return}const pieces=pattern.split(/\{(?:subject|object)\}/);if(pieces.some(p=>/[{}]/.test(p))||(slots.length===2&&!pieces[1])){$('language-status').textContent='Separate slots with literal words and use only the supported placeholders.';return}
 const op=$('language-operation').value;const rule={prefix:pieces[0],separator:slots.length===2?pieces[1]:'',suffix:pieces.at(-1),slots,operation:{op,subject:slots.includes('subject')?'{subject}':'',relation:$('language-relation').value.trim(),object:slots.includes('object')?'{object}':'',negative:false,conditions:[],text:''}};run('language_teach_pattern',{id:'taught:'+pattern,rule})};
 $('language-word-form').onsubmit=e=>{e.preventDefault();run('language_teach_word',{word:$('language-word').value.trim(),meaning:$('language-meaning').value.trim()})};
 const previous=render;render=function(s){previous(s);if(document.activeElement!==$('language-mode'))$('language-mode').value=graphState.language_mode||'hybrid';section.dataset.mode=graphState.language_mode||'hybrid';};
})();
