"""A small compositional, symbolic concept learner. Python 3.9+, no dependencies."""
import argparse
import json
import re
from pathlib import Path


class LanguageError(ValueError):
    pass


def noun(word):
    return word.lower()


class ConceptCategory:
    """The preorder category generated by declared subtype relationships.

    There is at most one morphism A -> B: evidence that every A is a B.
    Mutual inclusion does not force concept names to be identical.
    """

    def __init__(self):
        self.objects = set()
        self.generators = set()

    def add(self, source, target):
        self.objects.update((source, target))
        self.generators.add((source, target))

    def arrows(self):
        result = self.generators | {(x, x) for x in self.objects}
        while True:
            expanded = result | {(a, d) for a, b in result for c, d in result if b == c}
            if expanded == result:
                return result
            result = expanded

    def compose(self, first, second):
        arrows = self.arrows()
        if first not in arrows or second not in arrows or first[1] != second[0]:
            raise ValueError("Only existing morphisms with matching endpoints compose.")
        return first[0], second[1]


def parse(statement):
    """Compile the supported grammar to explicit semantic operations."""
    text = statement.strip().rstrip(".").strip()
    patterns = [
        ("definition", r"[Aa]n? (\w+) is an? (\w+) (?:who|that) (\w+) an? (\w+)"),
        ("subtype", r"[Aa]n? (\w+) is an? (\w+)"),
        ("instance", r"([A-Z]\w*) is an? (\w+)"),
        ("relation", r"([A-Z]\w*) (\w+) ([A-Z]\w*)"),
    ]
    for kind, pattern in patterns:
        match = re.fullmatch(pattern, text)
        if match:
            args = list(match.groups())
            if kind in ("definition", "subtype"):
                args = [noun(x) for x in args]
            elif kind == "instance":
                args[1] = noun(args[1])
            else:
                args[1] = noun(args[1])
                if args[1] in {"is", "not", "does", "can", "must"}:
                    break
            return kind, tuple(args)
    raise LanguageError("Unsupported sentence. Try 'Mira is a person', 'Mira grows Fern', "
                        "or 'A gardener is a person who grows a plant'.")


class MeaningSystem:
    def __init__(self):
        self.category = ConceptCategory()
        self.statements = []
        self.definitions = {}
        self.facts = {}
        self.entities = set()

    def tell(self, statement):
        kind, args = parse(statement)
        if kind == "definition" and args[0] in self.definitions:
            if self.definitions[args[0]][:3] != args[1:]:
                raise LanguageError("That concept already has a different definition.")
        if statement in self.statements:
            return "Already learned."
        self.statements.append(statement)
        if kind == "definition":
            concept, base, relation, target = args
            self.definitions[concept] = (base, relation, target, statement)
            self.category.add(concept, base)
            self.category.objects.add(target)
        elif kind == "subtype":
            self.category.add(*args)
        elif kind == "instance":
            entity, concept = args
            self.category.objects.add(concept)
            self.entities.add(entity)
            self.facts[("is", entity, concept)] = (statement, ())
        else:
            subject, relation, target = args
            self.entities.update((subject, target))
            self.facts[(relation, subject, target)] = (statement, ())
        self._infer()
        return "Learned: " + statement

    def _infer(self):
        # Finite, monotonic closure: no generated entities or arbitrary programs.
        while True:
            pending = {}
            for fact in list(self.facts):
                relation, entity, concept = fact
                if relation == "is":
                    for source, target in sorted(self.category.generators):
                        if source == concept:
                            pending.setdefault(("is", entity, target),
                                               (f"Every {source} is a {target}.", (fact,)))
            for concept, (base, relation, target, source) in self.definitions.items():
                for fact in list(self.facts):
                    rel, subject, obj = fact
                    premises = (("is", subject, base), fact, ("is", obj, target))
                    if rel == relation and all(p in self.facts for p in premises):
                        pending.setdefault(("is", subject, concept), (source, premises))
            new = {fact: proof for fact, proof in pending.items() if fact not in self.facts}
            if not new:
                return
            self.facts.update(new)

    def explain(self, fact, depth=0):
        source, premises = self.facts[fact]
        lines = ["  " * depth + source]
        for premise in premises:
            lines.extend(self.explain(premise, depth + 1))
        return lines

    def ask(self, question):
        text = question.strip().rstrip("?").strip()
        match = re.fullmatch(r"(?:Is|Why is) ([A-Z]\w*) an? (\w+)", text)
        if match:
            fact = ("is", match[1], noun(match[2]))
            if fact not in self.facts:
                return "Unknown: I cannot derive that from what I have learned."
            return "Yes.\n" + "\n".join(self.explain(fact))
        match = re.fullmatch(r"What is an? (\w+)", text)
        if match:
            concept = noun(match[1])
            if concept in self.definitions:
                return self.definitions[concept][3]
            parents = sorted(b for a, b in self.category.arrows() if a == concept and b != concept)
            return (f"A {concept} is a " + ", a ".join(parents) + ".") if parents else "No definition learned."
        match = re.fullmatch(r"What is ([A-Z]\w*)", text)
        if match:
            types = sorted(c for r, e, c in self.facts if r == "is" and e == match[1])
            return ", ".join(types) if types else "Unknown."
        raise LanguageError("Try 'Is Mira a gardener?', 'Why is Mira a gardener?', "
                            "'What is Mira?', or 'What is a gardener?'.")

    def save(self, path):
        path = Path(path)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(json.dumps({"statements": self.statements,
                                         "examples": getattr(self, "learner", None).examples
                                         if hasattr(self, "learner") else {}}, indent=2) + "\n")
        temporary.replace(path)

    @classmethod
    def load(cls, path):
        system = cls()
        path = Path(path)
        if path.exists():
            data = json.loads(path.read_text())
            for statement in (data if isinstance(data, list) else data["statements"]):
                system.tell(statement)
            if isinstance(data, dict):
                from adaptive import AdaptiveLearner
                system.learner = AdaptiveLearner(system)
                for concept, examples in data.get("examples", {}).items():
                    for entity, label in examples.items():
                        system.learner.teach(concept, entity, label)
        return system


DEMO = [
    "A gardener is a person who grows a plant.",
    "A rose is a plant.",
    "Mira is a person.",
    "Fern is a rose.",
    "Mira grows Fern.",
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--memory", type=Path, default=Path("memory.json"))
    args = parser.parse_args()
    system = MeaningSystem() if args.demo else MeaningSystem.load(args.memory)
    from adaptive import AdaptiveLearner
    if not hasattr(system, "learner"):
        system.learner = AdaptiveLearner(system)
    if args.demo:
        for statement in DEMO:
            print(system.tell(statement))
        print("\nIs Mira a gardener?\n" + system.ask("Is Mira a gardener?"))
        return
    print("Concept learner. Use capitalized entity names and singular nouns. /quit exits.")
    print("Learning: /example concept Entity yes|no; /hypotheses concept; /predict concept Entity")
    while True:
        try:
            line = input("> ").strip()
            if line == "/quit":
                break
            if not line:
                continue
            if line.startswith("/example "):
                parts = line.split()
                if len(parts) != 4 or parts[3] not in {"yes", "no"}:
                    raise LanguageError("Use /example concept Entity yes|no")
                system.learner.teach(parts[1], parts[2], parts[3] == "yes")
                system.save(args.memory)
                print(system.learner.inspect(parts[1]))
            elif line.startswith("/hypotheses "):
                parts = line.split()
                if len(parts) != 2:
                    raise LanguageError("Use /hypotheses concept")
                print(system.learner.inspect(parts[1]))
            elif line.startswith("/predict "):
                parts = line.split()
                if len(parts) != 3:
                    raise LanguageError("Use /predict concept Entity")
                print(system.learner.predict(parts[1], parts[2]))
            elif line.endswith("?"):
                print(system.ask(line))
            else:
                print(system.tell(line))
                system.save(args.memory)
        except ValueError as error:
            print(error)
        except (EOFError, KeyboardInterrupt):
            break


if __name__ == "__main__":
    main()
