(()=>{
 const page=$('page-tasks');page.innerHTML=`<div class="dashboard-heading"><div><div class="tiny-label">PERSISTENT WORK</div><h2>Pick up where you left off.</h2><p class="page-description">A saved request, a plan, and a record of each step. Questions and unfinished work stay attached to their task.</p></div></div><form id="task-plan-form"><label for="task-request">What should I do?</label><textarea id="task-request" rows="3" required maxlength="2000" placeholder="Start with 5, ask me what to add, then show the total."></textarea><button class="primary" type="submit">Plan task</button></form><p id="task-feedback" role="status"></p><details><summary>Supply taught steps directly</summary><p class="sense-hint">Each step names a taught method. Refer to an earlier result with {"var":"step_id"}. A task_input step asks for missing input. Start the saved plan when ready.</p><textarea id="task-steps" rows="7" aria-label="Task steps JSON" spellcheck="false">[{"id":"start","method":"sequence_value","argument":{"value":5}},{"id":"answer","method":"task_input","argument":{"question":"What should I add to 5?"}},{"id":"total","method":"sequence_add","argument":{"left":{"var":"start"},"right":{"var":"answer"}}}]</textarea><button class="secondary" id="task-save-steps">Save these steps</button></details><div id="task-list" class="task-list"></div><p class="sense-hint">Execution needs the server running. Completed steps are retained. An action interrupted by a restart requires review before retrying. Recurring or conditional tasks need corresponding taught procedures; this runner does not invent them.</p>`;
 async function run(name,argument){if(busy)return;$('task-feedback').textContent='Updating task…';await act('run_skill',null,{name,argument});$('task-feedback').textContent=$('error').textContent||'Task updated.'}
 async function create(steps){if(busy)return;const request=$('task-request').value.trim()||'Add to five';$('task-feedback').textContent='Preparing a saved plan…';await act('create_task',null,{request,...(steps===undefined?{}:{steps})});$('task-feedback').textContent=$('error').textContent||'Task saved. Inspect its steps below.'}
 $('task-plan-form').onsubmit=e=>{e.preventDefault();create()};$('task-save-steps').onclick=()=>{try{create(JSON.parse($('task-steps').value))}catch{$('task-feedback').textContent='Steps must be valid JSON.'}};
 const pretty=x=>typeof x==='string'?x:JSON.stringify(x,null,2);let seen='';const previous=render;render=function(state){previous(state);const tasks=graphState.tasks||[];const key=JSON.stringify(tasks);if(key===seen||(document.activeElement?.matches('input,textarea')&&document.activeElement.closest('#task-list')))return;seen=key;$('task-list').replaceChildren();
  if(!tasks.length)$('task-list').append(el('p','dashboard-empty','No saved tasks yet. Describe one above, or ask naturally in chat.'));
  for(const task of tasks.slice().reverse()){const card=el('article','task-card');card.dataset.status=task.status;const heading=el('div','dashboard-card-heading');heading.append(el('h3','',task.title),el('span','dashboard-badge',task.status.replaceAll('_',' ')));card.append(heading);
   card.append(el('p','sense-hint',task.completed.length+' of '+task.steps.length+' steps completed'));
   const list=el('ol','task-steps-list');for(const step of task.completed){const row=el('li','task-step-done');row.append(el('strong','','✓ '+step.id+' · '+step.method));const details=el('details');details.append(el('summary','','Saved result'),el('pre','',pretty(step.result)));row.append(details);list.append(row)}
   for(const [index,step]of task.pending.entries()){const row=el('li',index===0?'task-step-current':'');row.append(el('strong','',(index===0?'→ ':'')+step.id+' · '+step.method));const details=el('details');details.append(el('summary','','Input'),el('pre','',pretty(step.argument)));row.append(details);list.append(row)}card.append(list);
   if(task.error)card.append(el('p','dashboard-card-error',task.error));
   if(task.status==='needs_plan'){card.append(el('p','dashboard-card-error',task.question));const button=el('button','secondary','Revise request');button.onclick=()=>{$('task-request').value=task.original;$('task-request').focus()};card.append(button)}
   if(task.status==='waiting'){const form=el('form','task-answer-form');const label=el('label','',task.question);const input=el('input');input.required=true;input.setAttribute('aria-label','Answer for '+task.title);label.append(input);const send=el('button','primary','Answer and continue');send.type='submit';form.append(label,send);form.onsubmit=e=>{e.preventDefault();run('task_answer',{id:task.id,answer:input.value})};card.append(form)}
   const controls=el('div','dashboard-card-actions');if(['ready','paused','blocked','needs_review'].includes(task.status)){const resume=el('button','primary',task.status==='ready'?'Start task':task.status==='needs_review'?'Retry reviewed step':'Resume task');resume.onclick=()=>run('task_resume',{id:task.id});controls.append(resume)}if(['queued','waiting'].includes(task.status)){const pause=el('button','secondary','Pause');pause.onclick=()=>run('task_pause',{id:task.id});controls.append(pause)}if(!['completed','cancelled','running'].includes(task.status)){const cancel=el('button','secondary','Cancel');cancel.onclick=()=>run('task_cancel',{id:task.id});controls.append(cancel)}card.append(controls);
   if(task.pending.length&&['ready','paused','blocked','needs_review'].includes(task.status)){const details=el('details');details.append(el('summary','','Revise current step input'));const form=el('form');const input=el('textarea');input.rows=4;input.value=JSON.stringify(task.pending[0].argument,null,2);input.setAttribute('aria-label','Revised input for '+task.title);const save=el('button','secondary','Save revised input');save.type='submit';form.append(input,save);form.onsubmit=e=>{e.preventDefault();try{run('task_revise',{id:task.id,argument:JSON.parse(input.value)})}catch{$('task-feedback').textContent='Input must be valid JSON.'}};details.append(form);card.append(details)}
   const original=el('details');original.append(el('summary','','Original request'),el('p','dashboard-copy',task.original));card.append(original);$('task-list').append(card);
  }
 };
})();
