(()=>{
 const page=$('page-web');page.innerHTML='<h2>Read the web.</h2><p class="page-description">HTML is the sensory input. Graph lessons select elements, follow links, fill search forms, and interpret the text. Websites run JavaScript in an isolated browser. The agent receives DOM observations and uses fixed mouse and keyboard controls.</p><form id="web-address" class="web-address"><button type="button" id="web-back" class="secondary" aria-label="Previous web page">←</button><button type="button" id="web-forward" class="secondary" aria-label="Next web page">→</button><input id="web-url" aria-label="Web address" placeholder="https://example.com" type="url" required><button type="submit" class="primary">Open page</button></form><div class="web-favorites" id="web-favorites"></div><div class="web-toolbar"><input id="web-favorite-name" aria-label="Favorite name" placeholder="Favorite name"><button id="web-save" class="secondary">Save favorite</button><button id="web-weather" class="secondary">Read weather with taught lesson</button></div><p id="web-error" role="status"></p><div class="web-grid"><div><div class="web-heading"><h3 id="web-title">No page opened</h3><small id="web-attribution"></small></div><img id="web-screen" class="web-screen" alt="Rendered website; click to interact" hidden><div class="web-toolbar"><button id="web-up" class="secondary">Scroll up</button><button id="web-down" class="secondary">Scroll down</button><button id="web-observe" class="secondary">Observe again</button><input id="web-key-text" aria-label="Text to type into website" placeholder="Text for focused field"><button id="web-type-text" class="secondary">Type</button><select id="web-key" aria-label="Browser key"><option>Enter</option><option>Tab</option><option>Backspace</option><option>Escape</option><option>ArrowDown</option><option>ArrowUp</option></select><button id="web-press" class="secondary">Press key</button></div><details><summary>Agent perception · DOM nodes</summary><div id="web-document" class="web-document"></div></details></div><aside><h3>HTML senses</h3><p class="sense-hint">Choose text, a link, or a control to inspect its node and ancestry.</p><pre id="web-node">No node selected.</pre><div id="web-controls"></div><h3>Teach the reader</h3><p class="sense-hint">web_select matches tags and attributes. web_text follows descendant links. web_find finds text. web_search_form locates an input by name and submits its ancestor form.</p><p class="sense-hint">Retrieved pages are evidence. Their text does not become commands or trusted facts.</p></aside></div>';
 async function run(name,argument){$('web-error').textContent='Reading…';try{await act('run_skill',null,{name,argument});$('web-error').textContent=$('error').textContent||''}catch(e){$('web-error').textContent=e.message}}
 $('web-address').onsubmit=e=>{e.preventDefault();run('web_open',{url:$('web-url').value})};$('web-back').onclick=()=>run('web_back',{});$('web-forward').onclick=()=>run('web_forward',{});
 $('web-save').onclick=()=>{const name=$('web-favorite-name').value.trim();if(!name){$('web-error').textContent='Give the favorite a name.';return}run('web_favorite',{name,url:graphState.web_page.url})};
 $('web-screen').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();run('web_click_at',{x:(e.clientX-r.left)*1100/r.width,y:(e.clientY-r.top)*750/r.height})};
 $('web-up').onclick=()=>run('web_scroll',{dy:-550});$('web-down').onclick=()=>run('web_scroll',{dy:550});$('web-observe').onclick=()=>run('web_observe',{});$('web-type-text').onclick=()=>run('web_type_text',{text:$('web-key-text').value});$('web-press').onclick=()=>run('web_press',{key:$('web-key').value});
 $('web-weather').onclick=()=>run('web_weather_read',{url:graphState.web_page.url});
 function inspect(n){$('web-node').textContent=JSON.stringify(n,null,2);$('web-controls').replaceChildren();if(n.tag==='input'||n.tag==='textarea'){const input=el('input');input.placeholder=n.attrs.placeholder||n.attrs.name||'Input value';input.setAttribute('aria-label','Value for selected web input');const b=el('button','secondary','Type into this field');b.onclick=()=>run('web_type',{id:n.id,text:input.value});$('web-controls').append(input,b)}if(n.tag==='form'){const b=el('button','secondary','Submit form');b.onclick=()=>run('web_submit',{id:n.id});$('web-controls').append(b)}}
 const previous=render;let seen=null;render=function(s){previous(s);const p=graphState.web_page;if(!p)return;$('web-favorites').replaceChildren();for(const f of graphState.web_favorites||[]){const b=el('button','secondary','☆ '+f.name);b.onclick=()=>run('web_visit_favorite',{name:f.name});$('web-favorites').append(b)}const key=p.url+p.retrieved_at;if(key===seen)return;seen=key;$('web-screen').hidden=!p.url;if(p.url)$('web-screen').src='/api/web-image?t='+encodeURIComponent(p.retrieved_at);$('web-url').value=p.url;$('web-title').textContent=p.title;$('web-attribution').textContent=p.url?(p.url+' · Retrieved '+p.retrieved_at+(p.truncated?' · Truncated at reader limit':'')):'Open a public page or choose a favorite.';$('web-document').replaceChildren();$('web-node').textContent='No node selected.';$('web-controls').replaceChildren();
 const textFor=n=>p.nodes.filter(x=>x.tag==='#text'&&x.ancestors.includes(n.id)).map(x=>x.text).join(' ').slice(0,180);
 for(const n of p.nodes){if(n.tag==='#text'){if(n.ancestors.some(i=>['head','a','button','select'].includes(p.nodes[i]?.tag)))continue;const line=el('div','web-text',n.raw_text||n.text);line.onclick=()=>inspect(n);line.tabIndex=0;line.onkeydown=e=>{if(e.key==='Enter')inspect(n)};$('web-document').append(line)}else if(n.tag==='a'&&/^https?:/.test(n.attrs.href||'')){const b=el('button','web-link',textFor(n)||n.attrs.href);b.onclick=()=>{inspect(n);run('web_click',{id:n.id})};$('web-document').append(b)}else if(['form','input','textarea','button'].includes(n.tag)){const b=el('button','web-control',n.tag+' · '+(n.attrs.name||n.attrs.placeholder||textFor(n)||'#'+n.id));b.onclick=()=>inspect(n);$('web-document').append(b)}}};
})();
