(() => {
  const shell=el('div','app-shell');
  shell.innerHTML=`<aside class="app-nav"><div class="app-identity"><div class="identity-emblem" id="assistant-initials">A</div><div><div class="identity-name" id="assistant-label">Assistant</div><div class="tiny-label">Local intelligence</div></div></div><nav role="tablist" aria-label="Assistant workspace"></nav><div class="nav-bottom"><div class="live">● Local workspace</div><div id="local-connection">Connecting…</div><div style="margin-top:12px">Memory and methods<br>stay on this Mac.</div></div></aside><div class="app-main"><div class="app-bar"><div><div class="tiny-label">Your assistant / Workspace</div><h1 id="page-title">Conversation</h1></div><span class="pill">Persistent graph memory</span></div><div id="app-pages"></div></div>`;
  document.body.append(shell);
  const pages={},nav=shell.querySelector('nav');
  for(const [id,label,symbol] of [['conversation','Conversation','◌'],['dashboard','Dashboard','▦'],['memory','Memory','⌘'],['state','Internal state','◉'],['tasks','Tasks','☷'],['routines','Routines','↻'],['tools','Tools','⌁'],['web','Web','◎'],['teach','Teach & inspect','↗']]){
    const b=el('button','nav-tab');b.type='button';b.id='tab-'+id;b.setAttribute('role','tab');b.setAttribute('aria-controls','page-'+id);b.innerHTML=`<span class="nav-symbol">${symbol}</span><span>${label}</span>`;b.onclick=()=>openPage(id);nav.append(b);
    const p=el('section','app-page');p.id='page-'+id;p.setAttribute('role','tabpanel');p.setAttribute('aria-labelledby',b.id);pages[id]=p;$('app-pages').append(p);
  }
  function openPage(id){if(!pages[id])id='conversation';for(const [key,p]of Object.entries(pages)){p.hidden=key!==id;$('tab-'+key).setAttribute('aria-selected',String(key===id));}$('page-title').textContent=$('tab-'+id).lastElementChild.textContent;localStorage.setItem('assistant-page',id);if(id==='conversation')requestAnimationFrame(()=>{$('messages').scrollTop=$('messages').scrollHeight});}
  const conversation=document.querySelector('.workspace');const notebook=document.querySelector('.notebook');
  // Keep the graph authoring form, remove the obsolete toy-world interface.
  const authoring=$('graph-editor').closest('details');pages.teach.append(authoring);notebook.remove();
  const layout=el('div','conversation-layout');layout.append(conversation);const insights=el('aside','conversation-insights');
  insights.innerHTML='<div class="insight-card"><div class="tiny-label">Current state</div><h3 style="margin-top:8px">A view inside</h3><div id="state-glance"></div><button class="small-link" id="inspect-states">Inspect the causes ↗</button></div><div class="insight-card"><div class="tiny-label">Knowledge</div><div class="signal-row"><span>Connected facts</span><strong id="memory-total">—</strong></div><div class="signal-row"><span>Stored methods</span><strong id="method-total">—</strong></div><p>Ask, teach, or correct a connection. Previous knowledge stays in memory.</p></div><div class="insight-card"><div class="tiny-label">In the background</div><div id="routine-glance" class="signal-row">No active routines</div><button class="small-link" id="inspect-routines">Open routines ↗</button></div>';
  layout.append(insights);pages.conversation.append(layout);$('inspect-states').onclick=()=>openPage('state');$('inspect-routines').onclick=()=>openPage('routines');
  pages.memory.append(document.querySelector('.graph-workspace'));
  pages.teach.prepend(document.querySelector('.senses'));
  pages.state.innerHTML='<div class="state-heading"><div><h2>State, with a reason.</h2><p class="page-description">Persistent values updated by taught graph rules. Every change has a recorded cause.</p></div><button class="secondary" id="state-rules">Inspect update rules ↗</button></div><div class="state-grid" id="state-cards"></div><div class="state-cause" id="state-cause">The initial state has not been taught yet.</div><p class="section-note">Activation levels, 0–100. These functional signals are not probabilities or evidence of subjective feelings.</p><details><summary>Recent changes and evidence</summary><pre id="state-history"></pre></details>';
  $('state-rules').onclick=()=>{openPage('memory');graphNavigate('programs','affect_update')};
  pages.routines.innerHTML='<h2>A little initiative.</h2><p class="page-description">Graph routines can run after a delay and speak here when something needs your attention. Scheduled times survive a restart; execution needs this server running.</p><form id="reminder-form" class="routine-form"><label>What should I remind you?<input id="reminder-text" required maxlength="160" placeholder="Take a break"></label><label>After (seconds)<input id="reminder-delay" type="number" value="60" min="1" max="31536000" required></label><button class="primary" type="submit">Schedule reminder</button></form><p id="routine-feedback" role="status"></p><div id="routine-list"></div><details><summary>Build a different subroutine</summary><p>Teach a procedure, then schedule it with a name, input, delay, and optional repeat interval. Set repeat_seconds to 0 to run once.</p><pre>Run skill background_schedule: {"id":"my-routine","method":"your_taught_method","argument":null,"delay_seconds":60,"repeat_seconds":0}</pre></details>';
  $('reminder-form').onsubmit=async e=>{e.preventDefault();await act('run_skill',null,{name:'background_remind',argument:{text:$('reminder-text').value,after_seconds:Number($('reminder-delay').value)}});$('routine-feedback').textContent=$('error').textContent||'Reminder scheduled.'};
  const toolbar=el('div','tool-tabs');pages.tools.append(toolbar);const toolpanels={};
  for(const [id,label,selector]of [['code','Programming','.js-playground'],['sudoku','Sudoku canvas','.sudoku-panel']]){const p=document.querySelector(selector);toolpanels[id]=p;pages.tools.append(p);const b=el('button','tool-tab',label);b.type='button';b.onclick=()=>selectTool(id);b.dataset.tool=id;toolbar.append(b);}
  function selectTool(id){for(const [key,p]of Object.entries(toolpanels))p.hidden=key!==id;toolbar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tool===id)));}selectTool('code');
  document.querySelector('body>header')?.remove();document.querySelector('.intro')?.remove();document.querySelector('body>footer')?.remove();
  $('input').placeholder='Talk, teach something, or ask a question…';
  const oldRender=render;render=function(state){oldRender(state);const s=graphState;if(!s)return;const name=s.assistant_name||'Assistant';$('assistant-label').textContent=name;$('assistant-initials').textContent=name.split(' ').map(x=>x[0]).slice(0,2).join('');document.title=name+' · Assistant';$('local-connection').textContent=s.language_mode==='symbolic'?'Taught grammar · no Gemma fallback':s.connected?'Hybrid · Gemma available':'Connecting…';$('memory-total').textContent=s.facts.length.toLocaleString();$('method-total').textContent=Object.keys(s.procedures||{}).length.toLocaleString();
    const values=s.affect?.values||{};$('state-glance').replaceChildren();$('state-cards').replaceChildren();for(const [key,value]of Object.entries(values)){const row=el('div','signal-row');row.append(el('span','',key),el('strong','',String(value)));$('state-glance').append(row);const card=el('article','state-card');card.dataset.state=key;card.append(el('h3','',key),el('div','state-value',String(value)));const meter=document.createElement('progress');meter.max=100;meter.value=value;meter.setAttribute('aria-label',key+' activation');card.append(meter);$('state-cards').append(card);}
    const last=s.affect?.last;$('state-cause').textContent=last?'Last change · '+last.event.replaceAll('_',' ')+' — '+last.evidence:'Taught baseline. No conversation event has changed these values yet.';$('state-history').textContent=JSON.stringify(s.affect?.history||[],null,2);
    const jobs=s.subroutines||[];$('routine-glance').textContent=jobs.filter(j=>j.status==='scheduled').length+' scheduled';$('routine-list').replaceChildren();if(!jobs.length)$('routine-list').append(el('p','empty','No routines yet. Schedule one above.'));for(const job of jobs){const row=el('div','routine-row'),copy=el('div');copy.append(el('h3','',job.id),el('p','',job.status+' · '+job.method+' · '+new Date(job.next_at*1000).toLocaleString()));row.append(copy);if(job.status==='scheduled'){const cancel=el('button','secondary','Cancel');cancel.onclick=()=>act('run_skill',null,{name:'background_cancel',argument:{id:job.id}});row.append(cancel)}$('routine-list').append(row);}
  };
  openPage(location.hash==='#javascript-playground'?'tools':localStorage.getItem('assistant-page')||'conversation');
  // Read only updates: preserve drafts and do not repaint unchanged state.
  let polling=false;setInterval(async()=>{if(busy||polling||document.hidden)return;polling=true;try{const res=await fetch('/api/state?since='+encodeURIComponent(stateVersion||''));if(res.ok){const s=await res.json();if(s.state_version!==stateVersion)render(s)}}catch{}finally{polling=false}},5000);
})();
