// Long-term retained methods and task-local active methods are separate.
import fs from 'node:fs';import {G} from './graph.mjs';
const suite={};const save=(name,g,x)=>suite[name]={graph:{...g.finish(x),execution_budget:10000000},source:'Generic stored-effect retrieval and task-local eviction.'};
const call=(g,name,x)=>g.op('call',[x],{name});
const read=g=>g.op('act',[g.input,g.data({namespace:'knowledge.activation',key:'index'})],{surface:'workspace',action:'read'});
const write=(g,token,value)=>g.op('act',[token,g.rec({namespace:g.data('knowledge.activation'),key:g.data('index'),value})],{surface:'workspace',action:'write'});
let g=new G();save('activation_index_init',g,write(g,g.input,g.data([])));
// Compute the reusable effect signature once, when retention succeeds.
g=new G();const entry=g.input,example=g.item(g.get(entry,'validation'),g.data(0));
const signature=g.rec({name:g.get(entry,'name'),input_kind:g.op('kind_of',[g.get(example,'input')]),output_kind:g.op('kind_of',[g.get(example,'expected')]),effects:g.get(call(g,'priority_features',example),'features'),length:g.len(g.get(entry,'ops'))});
const old=read(g);save('activation_register',g,write(g,old,g.push(old,signature)));
// Compare generic changed-leaf paths and values; no environment names.
const match=new G(),a=match.get(match.input,'item'),b=match.get(match.input,'context');
const compatible=match.and(match.eq(match.get(a,'path'),match.get(b,'path')),match.eq(match.op('kind_of',[match.get(a,'value')]),match.op('kind_of',[match.get(b,'value')])));
const matchScore=match.choose(compatible,match.choose(match.eq(match.get(a,'value'),match.get(b,'value')),match.data(5),match.data(1)),match.data(0));
const effect=new G();const effectScore=call(effect,'priority_sum',effect.op('map',[effect.get(effect.input,'context'),effect.get(effect.input,'item')],{body:match.finish(matchScore)}));
const find=new G();const same=find.eq(find.get(find.input,'item','name'),find.get(find.input,'context'));
const rank=new G(),method=rank.get(rank.input,'item'),ctx=rank.get(rank.input,'context');
const record=rank.item(rank.op('filter',[rank.get(ctx,'catalog'),rank.get(method,'name')],{body:find.finish(same,'Bool')}),rank.data(0));
const overlap=call(rank,'priority_sum',rank.op('map',[rank.get(method,'effects'),rank.get(ctx,'features')],{body:effect.finish(effectScore)}));
const score=rank.calc('subtract',rank.calc('add',rank.calc('add',rank.calc('multiply',overlap,rank.data(1000)),rank.choose(rank.eq(rank.get(method,'output_kind'),rank.get(ctx,'output_kind')),rank.data(100),rank.data(0))),rank.get(record,'wins')),rank.calc('add',rank.calc('multiply',rank.get(method,'length'),rank.data(10)),rank.calc('multiply',rank.get(record,'misses'),rank.data(10))));
const ranked=rank.rec({name:rank.get(method,'name'),priority:rank.calc('subtract',rank.data(0),score),compatible:rank.datum(rank.eq(rank.get(method,'input_kind'),rank.get(ctx,'input_kind'))),overlap});
const keep=new G(),names=new G();g=new G();const index=read(g),first=g.item(g.get(g.input,'state','examples'),g.data(0));
const context=g.rec({catalog:g.get(g.input,'state','catalog'),features:g.get(first,'features'),input_kind:g.op('kind_of',[g.get(first,'input')]),output_kind:g.op('kind_of',[g.get(first,'expected')])});
const ranking=g.op('map',[index,context],{body:rank.finish(ranked)});
const eligible=g.op('filter',[ranking],{body:keep.finish(keep.and(keep.bool(keep.get(keep.input,'compatible')),keep.lt(keep.data(0),keep.get(keep.input,'overlap'))),'Bool')});
const top=g.op('slice',[g.op('sort',[eligible],{key:'priority'})],{start:0,stop:1});
const selected=g.choose(g.eq(g.get(g.input,'mode'),g.data('all_active')),g.op('map',[index],{body:names.finish(names.get(names.input,'name'))}),g.op('map',[top],{body:names.finish(names.get(names.input,'name'))}));
save('activation_select',g,g.rec({selected,ranking:g.choose(g.eq(g.get(g.input,'mode'),g.data('all_active')),g.data([]),ranking)}));
const stat=new G();g=new G();const state=call(g,'fair_init',g.input);
const selection=g.choose(g.eq(g.get(g.input,'mode'),g.data('no_memory')),g.data({selected:[],ranking:[]}),call(g,'activation_select',g.rec({state,mode:g.get(g.input,'mode')})));
const active=g.get(selection,'selected');
save('activation_init',g,g.rec({state,active,ranking:g.get(selection,'ranking'),route_stats:g.op('map',[active],{body:stat.finish(stat.rec({name:stat.input,best:stat.data(0),stalls:stat.data(0)}))})}));
// Evict after eight attempted candidates using a method fail to improve its
// best observed agreement. Eviction is task-local; index/catalog stay intact.
const update=new G(),r=update.get(update.input,'item'),u=update.get(update.input,'context');
const touched=update.and(update.bool(update.get(u,'allowed')),update.contains(update.get(u,'ops'),update.get(r,'name')));
const better=update.lt(update.get(r,'best'),update.get(u,'score'));
const changed=update.rec({name:update.get(r,'name'),best:update.choose(better,update.get(u,'score'),update.get(r,'best')),stalls:update.choose(better,update.data(0),update.calc('add',update.get(r,'stalls'),update.data(1)))});
const live=new G(),dead=new G(),statName=new G();g=new G();
const stats=g.op('map',[g.get(g.input,'stats'),g.input],{body:update.finish(update.choose(touched,changed,r))});
const living=g.op('filter',[stats],{body:live.finish(live.lt(live.get(live.input,'stalls'),live.data(8)),'Bool')});
const expired=g.op('filter',[stats],{body:dead.finish(dead.not(dead.lt(dead.get(dead.input,'stalls'),dead.data(8))),'Bool')});
save('activation_observe',g,g.rec({stats,active:g.op('map',[living],{body:statName.finish(statName.get(statName.input,'name'))}),evicted:g.op('map',[expired],{body:statName.finish(statName.get(statName.input,'name'))})}));
const put=(q,x,key,v)=>q.op('set_item',[x,q.data(key),v]);
g=new G();const initialized=call(g,'activation_init',g.input),baseState=g.get(initialized,'state');
const primitives=put(g,put(g,baseState,'vocabulary',g.get(g.input,'base')),'selected',g.data([]));
let working=put(g,put(g,baseState,'vocabulary',g.concat(g.get(initialized,'active'),g.get(g.input,'base'))),'selected',g.get(initialized,'active'));
for(const [key,v] of [['mode',g.get(g.input,'mode')],['active',g.get(initialized,'active')],['route_stats',g.get(initialized,'route_stats')],['evicted',g.data([])]])working=put(g,working,key,v);
save('activation_states',g,g.rec({working,primitives,active:g.get(initialized,'active'),ranking:g.get(initialized,'ranking')}));
g=new G();const p=call(g,'fair_init',g.input);save('activation_primitive_init',g,put(g,put(g,p,'vocabulary',g.get(g.input,'base')),'selected',g.data([])));
g=new G();save('activation_cap',g,g.rec({floor:g.data(100000),cap:g.choose(g.lt(g.data(100000),g.input),g.calc('subtract',g.input,g.data(100000)),g.data(0))}));
g=new G();const catalog=g.op('act',[g.input,g.data({namespace:'knowledge.economics',key:'catalog'})],{surface:'workspace',action:'read'});
const found=g.item(g.op('filter',[catalog,g.input],{body:find.finish(same,'Bool')}),g.data(0));save('activation_record',g,call(g,'activation_register',found));
const blockedOp=new G(),queueKeep=new G();
const blockedGraph=blockedOp.finish(blockedOp.datum(blockedOp.contains(blockedOp.get(blockedOp.input,'context'),blockedOp.get(blockedOp.input,'item'))));
const hasEvicted=(q,ops,evicted)=>q.contains(q.op('map',[ops,evicted],{body:blockedGraph}),q.data(true));
const keepQueue=queueKeep.finish(queueKeep.not(hasEvicted(queueKeep,queueKeep.get(queueKeep.input,'item','ops'),queueKeep.get(queueKeep.input,'context'))),'Bool');
const logged=new G();g=new G();const s=g.input;
const ops=g.push(g.get(s,'parent','ops'),g.item(g.get(s,'vocabulary'),g.get(s,'next_i')));
const canonical=g.get(call(g,'manager_canonicalize',g.rec({ops,catalog:g.get(s,'catalog')})),'ops');
const duplicate=g.contains(g.get(s,'seen'),canonical),length=g.len(canonical);
const allowed=g.and(g.and(g.not(duplicate),g.not(g.lt(g.get(s,'max_depth'),length))),g.not(hasEvicted(g,ops,g.get(s,'evicted'))));
const ev=g.choose(allowed,call(g,'priority_evaluate',g.rec({ops,examples:g.get(s,'examples'),predicate:g.get(s,'predicate'),projector:g.get(s,'projector')})),g.data({accepted:false,executable:false,progress:0,matches:0}));
const scaled=g.op('as_data',[g.op('floor',[g.num(g.calc('multiply',g.get(ev,'progress'),g.data(1000)))],{},'Number')]);
const priority=g.calc('subtract',length,g.calc('add',g.calc('multiply',g.get(ev,'matches'),g.data(1000000)),scaled));
const observed=g.choose(g.eq(g.get(s,'mode'),g.data('top_k')),call(g,'activation_observe',g.rec({stats:g.get(s,'route_stats'),ops,allowed:g.datum(allowed),score:g.calc('add',scaled,g.calc('multiply',g.get(ev,'matches'),g.data(1000000)))})),g.rec({stats:g.get(s,'route_stats'),active:g.get(s,'active'),evicted:g.get(s,'evicted')}));
const child=g.rec({ops,priority,next_i:g.data(0)});
const queued=g.choose(g.and(g.bool(g.get(ev,'executable')),g.lt(length,g.get(s,'max_depth'))),g.push(g.get(s,'queue'),child),g.get(s,'queue'));
const nextI=g.calc('add',g.get(s,'next_i'),g.data(1)),more=g.lt(nextI,g.len(g.get(s,'vocabulary')));
const root=g.eq(g.len(g.get(s,'parent','ops')),g.data(0)),rootContinues=g.and(root,more);
const returned=g.choose(g.and(g.not(root),more),g.push(queued,g.rec({ops:g.get(s,'parent','ops'),priority:g.get(s,'parent','priority'),next_i:nextI})),queued);
// Preserve queue age normally. Only truncate by score if the beam overflows.
const pruned=g.op('filter',[returned,g.get(observed,'evicted')],{body:keepQueue});
const bounded=g.choose(g.lt(g.get(s,'beam'),g.len(pruned)),g.op('slice',[g.op('sort',[pruned],{key:'priority'})],{start:0,stop:100}),pruned);
const empty=g.eq(g.len(bounded),g.data(0));
const choice=g.choose(g.and(g.not(rootContinues),g.not(empty)),call(g,'fair_choose',bounded),g.rec({parent:g.rec({ops:g.get(s,'parent','ops'),priority:g.get(s,'parent','priority'),next_i:nextI}),queue:bounded,band_size:g.data(0)}));
const done=g.op('or',[g.bool(g.get(ev,'accepted')),g.op('or',[g.and(g.not(rootContinues),empty),g.and(g.eq(g.get(s,'mode'),g.data('top_k')),g.eq(g.len(g.get(observed,'active')),g.data(0)))],{},'Bool')],{},'Bool');
save('activation_step',g,g.rec({mode:g.get(s,'mode'),active:g.get(observed,'active'),route_stats:g.get(observed,'stats'),evicted:g.get(observed,'evicted'),vocabulary:g.get(s,'vocabulary'),catalog:g.get(s,'catalog'),selected:g.get(s,'selected'),examples:g.get(s,'examples'),predicate:g.get(s,'predicate'),projector:g.get(s,'projector'),max_depth:g.get(s,'max_depth'),beam:g.get(s,'beam'),parent:g.get(choice,'parent'),next_i:g.get(choice,'parent','next_i'),queue:g.get(choice,'queue'),seen:g.choose(allowed,g.push(g.get(s,'seen'),canonical),g.get(s,'seen')),found:g.choose(g.bool(g.get(ev,'accepted')),ops,g.data(null)),done:g.datum(done),evaluated:g.calc('add',g.get(s,'evaluated'),g.choose(allowed,g.data(1),g.data(0))),last:ops,last_expanded:canonical,last_duplicate:g.datum(duplicate),last_allowed:g.datum(allowed),last_evaluation:ev,last_parent:g.get(s,'parent','ops'),last_child_index:g.get(s,'next_i'),last_band_size:g.get(choice,'band_size'),last_log:g.choose(allowed,g.op('map',[ops],{body:logged.finish(logged.rec({ops:logged.list(logged.input)}))}),g.data([]))}));
fs.writeFileSync(new URL('../curriculum/activation-search.json',import.meta.url),JSON.stringify(suite,null,2)+'\n');
